[package]
name = "kiwi-api"
version = "0.1.0"
authors = ["Jacob Halsey <jacob@jhalsey.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
config = "0.9"
serde = { version = "1.0.115", features = ["derive"] }
diesel = { version = "1.4.5", features = ["postgres", "r2d2", "chrono"] }
r2d2 = "0.8.4"

#futures = "0.1.27"      # Rust-lang-nursery futures
#failure = "0.1.5"       # Rust-lang-nursery improved error management
#actix-web = "1.0.3"     # The Web Server
#actix-web-httpauth = "0.3.1"    # Middleware for validating Basic Auth Header
#actix-multipart = "0.1.2"   # Multipart forms

#env_logger = "0.6"  # Implementation of the log crate
#chrono = "0.4.6"    # Time library
#serde_json = "1.0"  # Implementation of Serde for JSON
#serde_urlencoded = "0.5.5" # Serde for URL encoded query
#bincode = "1.1.4"   # Implementation of Serde for Binary
#validator = "0.8.0" # Struct Validation
#validator_derive = "0.8.0"
#bcrypt = "0.4.0"    # Password hashing
#rand = "0.6.5"      # Random number generation
#base64 = "0.10.1"
