[app]
port = 9000
storage_folder = "/storage"
contact_mailbox = "destination"
password_reset_url = "https://admin.kiwijoinerydevon.co.uk/password_reset"
api_url = "http://localhost:9000"

[database]
host = "localhost"
port = 5432
username = "username"
password = "password"
name = "kiwi"

[mailer]
host = "mail.contoso.com"
port = 587
email = "email@contoso.com"
password = "password"
