// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::*;
use chrono::offset::Utc;
use chrono::DateTime;

// https://github.com/diesel-rs/diesel/blob/master/guide_drafts/trait_derives.md#identifiable
// Note that Identifiable assumes: #[primary_key(id)]

#[derive(Debug, Clone, Queryable, Identifiable, AsChangeset)]
#[changeset_options(treat_none_as_null = "true")]
pub struct User {
    pub id: i32,
    pub name: String,
    pub email: String,
    pub password_hash: Option<String>,
    pub password_reset_token: Option<String>,
}

#[derive(Debug, Insertable)]
#[table_name = "users"]
pub struct NewUser {
    pub name: String,
    pub email: String,
    pub password_hash: Option<String>,
    pub password_reset_token: Option<String>,
}

#[derive(Debug, Queryable, Identifiable, Associations)]
#[belongs_to(User)]
pub struct Session {
    pub id: i32,
    pub user_id: i32,
    pub token: String,
    pub created: DateTime<Utc>,
    pub last_used: DateTime<Utc>,
    pub last_ip: Vec<u8>,
    pub user_agent: String,
}

#[derive(Debug, Insertable)]
#[table_name = "sessions"]
pub struct NewSession {
    pub user_id: i32,
    pub token: String,
    pub last_ip: Vec<u8>,
    pub user_agent: String,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct File {
    pub id: i32,
    pub size: i32,
    pub extension: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(item_id, file_id)]
pub struct GalleryFile {
    pub item_id: i32,
    pub file_id: i32,
    pub height: i32,
    pub width: i32,
}

#[derive()]
pub struct GalleryItem {
    pub id: i32,
    pub description: Option<String>,
    pub original_file_id: i32,
    pub position: String,
    pub category: String,
}
