// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::{DateTime, Utc};
use crate::schema::*;

// https://github.com/diesel-rs/diesel/blob/master/guide_drafts/trait_derives.md#identifiable
// Note that Identifiable assumes: #[primary_key(id)]

#[derive(Debug, Clone, Queryable, Identifiable, AsChangeset)]
#[changeset_options(treat_none_as_null="true")]
pub struct User {
    pub id: i32,
    pub name: String,
    pub email: String,
    pub password_hash: Option<String>,
    pub is_admin: bool,
    pub password_reset_token: Option<String>,
}

#[derive(Debug, Insertable)]
#[table_name="users"]
pub struct NewUser {
    pub name: String,
    pub email: String,
    pub password_hash: Option<String>,
    pub is_admin: bool,
    pub password_reset_token: Option<String>,
}

#[derive(Debug, Queryable, Identifiable, Associations)]
#[belongs_to(User)]
pub struct Session {
    pub id: i32,
    pub user_id: i32,
    pub token: String,
    pub created: DateTime<Utc>,
    pub last_used: DateTime<Utc>,
    pub last_ip: Vec<u8>,
    pub user_agent: String,
}

#[derive(Debug, Insertable)]
#[table_name="sessions"]
pub struct NewSession {
    pub user_id: i32,
    pub token: String,
    pub last_ip: Vec<u8>,
    pub user_agent: String,
}

#[derive(Queryable, Debug, Identifiable, Associations)]
#[belongs_to(User)]
pub struct Lecture {
    pub id: i32,
    pub user_id: i32,
    pub name: String,
}
